name: Add competitor to list when confirmed by tag

on:
  workflow_dispatch:
jobs:
    
  add-competitor:
    if: >
      contains(github.event.issue.labels.*.name, 'registration') &&
      contains(github.event.issue.labels.*.name, 'accepted')

    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event
        run: echo '${{ toJson(github.event) }}'
        
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Isolate repo link
        run: bash .github/repo_regex.sh "${{ github.event.issue.body }}" "${{ github.event.issue.user.login }}"

      - name: Add competitor to file
        run: echo "${{ github.event.issue.number }}:$USER_REPO" >> competitors.txt

      - name: Commit files
        run: |
            git config user.email "example@example.com"
            git config user.name "Benchmark_Acceptor"
            git add competitors.txt
            git commit -m "Here comes a new challenger!"
            git push

      - uses: peter-evans/close-issue@v1
        with:
          comment: |
            #### Here comes a new challenger!
            You have been added to the benchmark leaderboard.

      - name: Controller (re-)evaluation comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Your ranking is going to be updated at regular intervals.

            If you want us to re-evaluate your controller at any time, add a new comment containing the word "run".
            If you want to unsubscribe your repository from the list, add a new comment containing the word "unsubscribe".

            Please note that the commands might take a few minutes before posting feedback messages. Refreshing the page can help seeing newer messages.
