name: Individual competitor evaluation of their controller

run-name: "Individual evaluation of competitor ${{ github.event.issue.number }} : ${{ github.event.issue.user.login }}"

on: 
  issue_comment:
    types: [created]

jobs:
  feedback_message:
    if: >
      contains(github.event.issue.labels.*.name, 'registration') &&
      contains(github.event.issue.labels.*.name, 'accepted') &&
      github.event.issue.user.login == github.event.comment.user.login &&
      contains(github.event.comment.body, 'run')
    runs-on: ubuntu-latest
    steps:
      - name: Feedback on individual evaluation
        id: feedback
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Individual re-evaluation in progress...
    outputs:
      comment-id: ${{ steps.feedback.outputs.comment-id }}
  record:
    needs: feedback_message
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Isolate repo link
        run: |
          solo_reference=$( grep ./competitors.txt -e '^${{ github.event.issue.number }}:.*' )
          echo $solo_reference
          echo "INDIVIDUAL_REF=$solo_reference" >> $GITHUB_ENV

      - name: Fetch default controller name
        run: bash .github/default_controller_name_regex.sh
        continue-on-error: true

      - name: Record and update Benchmark animations
        id: webots_test
        uses: cyberbotics/benchmark-record-action@forkSystem 
        with:
          fetch_token: ${{ secrets.REPO_TOKEN }}
          individual_evaluation: "${{ env.INDIVIDUAL_REF }}"
          default_controller_name: ${{ env.DEFAULT_CONTROLLER }}
        continue-on-error: true

      - name: Feedback on success
        if: ${{ steps.webots_test.outcome == 'success' }}
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          comment-id: ${{ needs.feedback_message.outputs.comment-id }}
          body: Re-evaluation finished! The leaderboard is up to date.

      - name: Feedback on failure
        if: ${{ steps.webots_test.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          comment-id: ${{ needs.feedback_message.outputs.comment-id }}
          body: There was a problem. Look at action logs for more details


      - name: Delete request comment
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}
        env:
          GH_TOKEN: ${{ github.token }}
