name: Record and update all competitors' performances
run-name: "General evaluation of all competitors"

on:
  workflow_dispatch:
# Uncomment to run every midnight
#  schedule:
#    - cron:  '0 0 * * *'
jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Fetch default controller name
        run: bash .github/default_controller_name_regex.sh
        continue-on-error: true

      - name: Record and update Benchmark animations
        uses: cyberbotics/benchmark-record-action@forkSystem 
        with:
          fetch_token: ${{ secrets.REPO_TOKEN }}
          default_controller_name: ${{ env.DEFAULT_CONTROLLER }}